poll/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('pollapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pollapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('polls/', views.polls_list, name='polls_list'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'), 
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('create/', views.create_poll, name='create_poll'),
    path('poll/<int:poll_id>/delete/', views.delete_poll, name='delete_poll'),
    path('<int:poll_id>/', views.polls_detail, name='polls_detail'),
    path('<int:poll_id>/results/', views.poll_results, name='poll_results'),  
    path('random_poll/', views.random_poll, name='random_poll'),
]

pollapp/models.py
from django.db import models
from django.contrib.auth.models import User
import random

# 数据库中创建两个table
class Poll(models.Model):
    # 投票问题部分的元素： title, description, 创建者， 创建时间，结束时间
    title = models.CharField(max_length=200)  # 投票标题
    description = models.TextField(blank=True, null=True)  # 投票描述
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)  # 创建者
    created_at = models.DateTimeField(auto_now_add=True)  # 创建时间
    end_date = models.DateTimeField()  # 投票结束时间

class Choice(models.Model):
    # 选择部分的元素：和poll连接，choice, 投票数
    poll = models.ForeignKey(Poll, related_name='choices', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)  # 选项内容
    votes = models.IntegerField(default=0)  # 投票数

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)

    def assign_random_avatar(self):
        avatars = [
            'avatars/avatar1.png',
            'avatars/avatar2.png',
            'avatars/avatar3.png',
            'avatars/avatar4.png',
            'avatars/avatar5.png',
            'avatars/avatar6.png',
            'avatars/avatar7.png',
            'avatars/avatar8.png',
            'avatars/avatar9.png',
            'avatars/avatar10.png',
            'avatars/avatar11.png',
            'avatars/avatar12.png',
        ]
        self.avatar = random.choice(avatars)

    def save(self, *args, **kwargs):
        if not self.avatar:
            self.assign_random_avatar()
        super().save(*args, **kwargs)

pollapp/forms.py
from django import forms
from .models import Poll, Choice
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError

class PollForm(forms.ModelForm):
    end_date = forms.DateTimeField(
        input_formats=['%Y-%m-%dT%H:%M'],
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'})
    )

    title = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter your question here'})
    )
    class Meta:
        model = Poll
        fields = ['title', 'description', 'end_date']

class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']

class RegisterForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': ' '})
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': ' '})
    )

    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': ' '}),
        }
        error_messages = {
            'username': {
                'max_length': "Username must be 150 characters or fewer.",
                'invalid': "Only letters, digits, and @/./+/-/_ are allowed in the username.",
                'required': "Username is required. Please enter a valid username."
            },
        }

    def clean_password(self):
        password = self.cleaned_data.get('password')
        try:
            validate_password(password)
        except ValidationError as e:
            self.add_error('password', e)
   
class RegisterForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': ' '}),
        help_text="Your password must be at least 8 characters long and not entirely numeric.",
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': ' '}),
        label="Confirm Password"
    )

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': ' '}),
        }
        error_messages = {
            'username': {
                'max_length': "Username must be 150 characters or fewer.",
                'invalid': "Only letters, digits, and @/./+/-/_ are allowed in the username.",
                'required': "Username is required. Please enter a valid username."
            },
        }

    def clean_password(self):
        password = self.cleaned_data.get('password')
        try:
            validate_password(password)
        except ValidationError as e:
            raise ValidationError(e)
        return password

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise ValidationError({
                'confirm_password': "Passwords do not match. Please try again."
            })

        return cleaned_data

pollapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Poll
from django.contrib.auth.decorators import login_required
from .forms import PollForm, ChoiceForm, RegisterForm
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth import login
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from .models import UserProfile


import random

def home(request):
    polls = Poll.objects.all()[:2]
    return render(request, 'pollapp/home.html', {'polls': polls})

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        print(f"User profile created for {instance.username}")
        profile = UserProfile.objects.create(user=instance)
        profile.assign_random_avatar()
        profile.save()

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            messages.success(request, "Registration successful! Please log in.")
            return redirect('login')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, error)
            # 重定向回注册页面
            return redirect(reverse('register'))
    else:
        form = RegisterForm()
    return render(request, 'pollapp/register.html', {'form': form})


def login_view(request):
    form = AuthenticationForm(request, data=request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "Invalid username or password. Please try again.")
            return HttpResponseRedirect(reverse('login')) 

    return render(request, 'pollapp/login.html', {'form': form})


def random_poll(request):
    polls = Poll.objects.all()
    if polls.exists():
        random_poll = random.choice(polls)
        return redirect('polls_detail', poll_id=random_poll.id)
    else:
        return redirect('polls_list')


@login_required
def create_poll(request):
    if request.method == 'POST':
        poll_form = PollForm(request.POST)

        choice_texts = [value for key, value in request.POST.items() if 'choice_text' in key]
        choice_forms = [ChoiceForm({'choice_text': text}) for text in choice_texts]

        if poll_form.is_valid() and all(cf.is_valid() for cf in choice_forms):
            poll = poll_form.save(commit=False)
            poll.created_by = request.user
            poll.save()
            
            for cf in choice_forms:
                choice = cf.save(commit=False)
                choice.poll = poll
                choice.save()
            
            return redirect('polls_list')
    else:
        poll_form = PollForm()
        choice_forms = [ChoiceForm(prefix=str(i)) for i in range(3)]
        
        for i, choice_form in enumerate(choice_forms, start=1):
            choice_form.fields['choice_text'].widget.attrs.update({'placeholder': f"Option {i}", 'class': 'choice-input'})

    return render(request, 'pollapp/create_poll.html', {
        'poll_form': poll_form,
        'choice_forms': choice_forms,
    })

@login_required
def delete_poll(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)

    if request.method == 'POST':
        poll.delete()
        return redirect('polls_list')
    messages.success(request, "Poll deleted successfully!")
    return redirect('polls_list')

def polls_list(request):
    query = request.GET.get('q')
    polls = Poll.objects.all().order_by('-created_at')

    if query:
        polls = polls.filter(Q(title__icontains=query))

    paginator = Paginator(polls, 10)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    return render(request, 'pollapp/polls_list.html', {'page_obj': page_obj, 'query': query})

def polls_detail(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    if request.method == 'POST':
        choice_id = request.POST.get('choice')
        choice = poll.choices.get(pk=choice_id)
        choice.votes += 1
        choice.save()
        return redirect('poll_results', poll_id=poll.id)
    return render(request, 'pollapp/polls_detail.html', {'poll': poll})

def poll_results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    share_link = request.build_absolute_uri(f'/{poll_id}/')
    choices = poll.choices.all()
    choice_data = [{'text': choice.choice_text, 'votes': choice.votes} for choice in choices]
    
    return render(request, 'pollapp/poll_results.html', {
        'poll': poll,
        'choice_data': choice_data,
        'share_link': share_link,
    })

pollapp/templates/pollapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta property="og:title" content="Vocalize - Create and Share Polls">
  <meta property="og:description" content="Vote Now, Share Your Voice">
  <meta property="og:image" content="{% static 'images/share-image.png' %}">
  <meta property="og:url" content="https://vocalize.up.railway.app/">
  <meta property="og:type" content="website">

  <title>{% block title %}Polling{% endblock %}</title>
  
  
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">

</head>
<body>
  <div class="base-container">
    <div>
      <header>
        <nav>
          <a href="{% url 'home' %}" class="nav-brand">Vocalize</a>
          <div class="nav-list" id="nav-list">
            <div class="left-link">
              <a href="{% url 'home' %}">Home</a>
              <a href="{% url 'create_poll' %}">Create Poll</a>
              <a href="{% url 'polls_list' %}">Polls</a>
            </div>
        
            <div class="right-link">
              {% if user.is_authenticated %}
              <div class="user-avatar">
                <img src="{{ user.userprofile.avatar.url }}" alt="Avatar" class="avatar-img">
                <div class="user-menu">
                  <p>{{ user.username }}</p>
                  <form action="{% url 'logout' %}" method="post" class="logout-form">
                    {% csrf_token %}
                    <button type="submit" class="logout-btn">Logout</button>
                  </form>
                </div>
              </div>
              {% else %}
              <a href="{% url 'login' %}" class="login">Log in</a>
              <a href="{% url 'register' %}" class="sign-up">Sign up</a>
              {% endif %}
            </div>
          </div>
          <button id="menu-toggle" class="menu-toggle">
            <i class="fa-solid fa-bars"></i>
          </button>
        </nav>
        
    </header>

    <main>
      {% block content %}{% endblock %}
    </main>

  </div>

</div>
  <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

pollapp/templates/pollapp/create_poll.html
{% extends "pollapp/base.html" %}
{% load static %}

{% block title %}Create Poll{% endblock %}
{% block content %}
<div class="create-poll-container">
    <div class="create-card">

        <h1>Create a New Poll</h1>
        <form method="post">
            {% csrf_token %}
            
            <div class="title">
      
                <label for="id_title">Title</label>
                {{ poll_form.title}}
            </div>

            <div id="choices-container" class="choices" data-initial-option-count="{{ initial_option_count }}">
                <p>Answer Options</p>
                <p id="option-limit-message" style="color: red; display: none;">Only up to 6 options can be added.</p>
                
                {% for choice_form in choice_forms %}
                    <div class="choice-option">
                        <div class="input-container">
                            {{ choice_form.choice_text }}
                            <span class="delete-option" onclick="removeChoice(this)">✕</span>
                        </div>
                    </div>
                {% endfor %}
            
                <button type="button" id="add-option-btn">+ Add Option</button>
            </div>
            
            <div class="end-date">
                <label for="id_end_date">End Date</label>
                {{ poll_form.end_date }}
            </div>
            
            <div class="buttons">
                <button type="submit">Create Poll</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

pollapp/templates/pollapp/home.html
{% extends "pollapp/base.html" %}
{% load static %}

{% block title %}Home{% endblock %}
{% block content %}

<div class="home-container">
  <div class="hero">
      <header class="big-title">
          <h1>Vote Now</h1>
          <h1>Share Your <span>Voice</span></h1>
      </header>

      <div class="call-link">
          <a href="{% url 'create_poll' %}" class="create-btn">Create Poll</a>
          <a href="{% url 'random_poll' %}" class="demo-btn">Live Demo</a>
      </div>
  </div>

  <ul class="polls-list">
      {% for poll in polls %}
          <li class="poll-card {% cycle 'poll-card-one' 'poll-card-two' %}">
              <a href="{% url 'polls_detail' poll.id %}" class="poll-title">{{ poll.title }}</a>

              <ul>
                  {% for choice in poll.choices.all %}
                  <li class="poll-choice">
                      <input type="radio" id="choice_{{ choice.id }}" name="choice" value="{{ choice.id }}" required>
                      <label for="choice_{{ choice.id }}">{{ choice.choice_text }}</label>
                  </li>
                  {% endfor %}
              </ul>

              <a href="{% url 'polls_detail' poll.id %}" class="vote-link">Go to Vote &rarr;</a>
          </li>
      {% empty %}
          <li>No polls available.</li>
      {% endfor %}
  </ul>
</div>

  <footer>
    <div class="social-links">
      <a href="mailto:skylarhyn@gmail.com" target="_blank" class="social-icon">
        <i class="fas fa-envelope"></i>
      </a>
      <a href="https://skylarhu.atwebpages.com/" target="_blank" class="social-icon" rel="noopener noreferrer">
        <i class="fas fa-globe"></i>
      </a>
      <a href="https://github.com/SkylarYHU" target="_blank" class="social-icon" rel="noopener noreferrer">
        <i class="fab fa-github"></i>
      </a>
      <a href="https://www.linkedin.com/in/skylar-hu/" target="_blank" class="social-icon" rel="noopener noreferrer">
        <i class="fab fa-linkedin"></i>
      </a>
    </div>

    <p>&copy; 2024 Vocalize - Made by Skylar Hu</p>
  </footer>

{% endblock %}

pollapp/templates/pollapp/login.html
{% extends "pollapp/base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="login-container">
    <div class="login-card">
        <h1>Login</h1>
        <p>Enter your details to get sign in to your account</p>

        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <input type="text" name="username" id="username" placeholder="Username" required>
            <input type="password" name="password" id="password" placeholder="Password" required>

            {% if messages %}
            <div>
                {% for message in messages %}
                    <div class="{% if message.tags %}{{ message.tags }}-message{% endif %}">
                        <p>{{ message }}</p>
                    </div>
                {% endfor %}
            </div>
            {% endif %}

            <button type="submit">Sign in</button>
        </form>
        <p>Don't have an account? <a href="{% url 'register' %}" class="register-link">Register now</a></p>
    </div>
</div>

{% endblock %}

pollapp/templates/pollapp/poll_results.html
{% extends "pollapp/base.html" %}
{% load static %}

{% block title %}Poll Results{% endblock %}
{% block content %}
<div class="poll-result-container">
    <div class="result-card">
       
        <h1>{{ poll.title }}</h1>
        <div class="result-chart">
            <canvas id="doughnutChart"></canvas>
        </div>
   
        <p>*Hover over the pie chart to see the percentage of each option.</p>
        <div class="btn-group">
            <a href="{% url 'polls_detail' poll.id %}" class="back-btn">Back to Poll</a>
            <button onclick="document.getElementById('shareModal').style.display = 'block'" class="share-btn">Share Poll</button>
        </div>

        <div class="share-modal" id="shareModal">
            <button onclick="closeShareModal()" class="close-btn"><i class="fa-solid fa-rectangle-xmark"></i></button>

            <div class="share-card">
                <div class="share-section share-left">
                    <h3>Share via link</h3>
                    <div class="share-link">
                        <input type="text" id="shareLink" value="{{ share_link }}" readonly>
                        <button id="copy-btn" onclick="copyToClipboard()"><i class="fa-solid fa-copy"></i></button>
                    
                    </div>
                </div>
            
                <div class="share-section share-right">
                    <div class="social-icons">
                        <a href="https://twitter.com/share?url={{ share_link }}" target="_blank" class="social-btn twitter">
                            <i class="fa-brands fa-x-twitter"></i>
                        </a>
                        <a href="https://www.facebook.com/sharer/sharer.php?u={{ share_link }}" target="_blank" class="social-btn facebook">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a href="https://reddit.com/submit?url={{ share_link }}" target="_blank" class="social-btn reddit">
                            <i class="fa-brands fa-reddit"></i>
                        </a>
                    </div>                    
                </div>

            </div>
        </div>
        
    </div>  
</div> 
    <script>
        const choiceData = {{ choice_data|safe }};
    </script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'js/charts.js' %}"></script> 
  
{% endblock %}

pollapp/templates/pollapp/polls_detail.html
{% extends "pollapp/base.html" %}
{% load static %}

{% block title %}Poll Detail{% endblock %}
{% block content %}
<div class="poll-detail-container">
  <div class="poll-detail-card">
    <h1>{{ poll.title }}</h1>
    <div class="detail-info">
      <p>
        <em>Created by {{ poll.created_by }}</em> /
        <em>Ends <span>{{ poll.end_date|date:"M d, Y H:i" }}</span></em>
      </p>
    </div>

    <form method="post">
      {% csrf_token %}
      <ul>
        {% for choice in poll.choices.all %}
          <li class="poll-choice">
            <input type="radio" id="choice_{{ choice.id }}" name="choice" value="{{ choice.id }}" required>
            <label for="choice_{{ choice.id }}">{{ choice.choice_text }}</label>
          </li>
        {% endfor %}
      </ul>
      <div class="btn-group">
        <button type="submit" class="vote-btn">Vote</button>
        <a href="{% url 'poll_results' poll.id %}" class="result-btn">View results</a>
      </div>
    </form>
  </div>

  {% if poll.created_by == request.user %}
  <form action="{% url 'delete_poll' poll.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this poll?');" class="delete-form">
    {% csrf_token %}
    <button type="submit" class="delete-btn">Remove Poll</button>
  </form>
  {% endif %}
</div>
{% endblock %}

pollapp/templates/pollapp/polls_list.html
{% extends "pollapp/base.html" %}
{% load static %}

{% block title %}Poll List{% endblock %}
{% block content %}

<div class="polls-list-container">
  <h1>All Polls</h1>

  <form method="get" class="search-bar">
    
    <input type="text" name="q" id="search-input" placeholder="Search polls..." value="{{ query|default:'' }}">
    <button class="clear-btn" id="clear-btn" type="button"><i class="fa-solid fa-xmark"></i></button>
    <button type="submit" class="search-btn"><i class="fa fa-search"></i></button>
  </form>

  <div class="poll-list">
    {% for poll in page_obj %}
      <div class="poll-item">
        <h2>{{ poll.title }}</h2>

        <ul>
          {% for choice in poll.choices.all %}
          <li class="poll-choice">
              <input type="radio" id="choice_{{ choice.id }}" name="choice" value="{{ choice.id }}" required>
              <label for="choice_{{ choice.id }}">{{ choice.choice_text }}</label>
          </li>
          {% endfor %}
        </ul>

        <div class="poll-info">
          <a href="{% url 'polls_detail' poll.id %}">View Poll</a>
          <p>Created by {{ poll.created_by }}</p>
        </div>
      </div>
    {% empty %}
    <p class="empty-message">No polls available.</p>
    {% endfor %}
  </div>  

  <div class="pagination">
    <form method="get" class="pagination-form">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
        {% else %}
            <span class="disabled">&lt;</span>
        {% endif %}

        <input type="number" name="page" value="{{ page_obj.number }}" min="1" max="{{ page_obj.paginator.num_pages }}" onchange="this.form.submit()" />
        
        <span>of {{ page_obj.paginator.num_pages }}</span>
        
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
        {% else %}
            <span class="disabled">&gt;</span>
        {% endif %}
    </form>
  </div>
</div>
{% endblock %}

pollapp/templates/pollapp/register.html
{% extends "pollapp/base.html" %}
{% load static %}

{% block title %}Sign up{% endblock %}
{% block content %}
<div class="register-container">
  <div class="register-card">

    <h1>Sign up</h1>
    <p>Create your account and join our community</p>

    <form method="post" action="{% url 'register' %}">
        {% csrf_token %}
        <div class="register-form">
          <div class="input-group">
            {{ form.username }}
            <label for="id_username">Username</label>
            {% if form.username.errors %}
                <div class="error-message">
                    {% for error in form.username.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
          </div>

          <div class="input-group">
              {{ form.password }}
              <label for="id_password">Password</label>
              {% if form.password.errors %}
                  <div class="error-message">
                      {% for error in form.password.errors %}
                          <p>{{ error }}</p>
                      {% endfor %}
                  </div>
              {% endif %}
          </div>  

          <div class="input-group">
              {{ form.confirm_password }}
              <label for="id_confirm_password">Confirm Password</label>
              {% if form.confirm_password.errors %}
                  <div class="error-message">
                      {% for error in form.confirm_password.errors %}
                          <p>{{ error }}</p>
                      {% endfor %}
                  </div>
              {% endif %}
          </div>

          {% if messages %}
          <div>
              {% for message in messages %}
                <div class="{% if message.tags %}{{ message.tags }}-message{% endif %}">
                  <p>{{ message }}</p>
                </div>
              {% endfor %}
          </div>
          {% endif %}

          <button type="submit">Sign up</button>
        </div>
    </form>
    <p>Already have an account? <a href="{% url 'login' %}" class="register-link">Log in</a></p>
  </div>
</div>
{% endblock %}